import { ArrowRight, BookOpenCheck, Plus, RadioTower, Send, ShieldCheck, Trash2, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { guideApi, type CollaborationCase, type GuideCorrection, type GuideProfile, type TakeoverLog } from "../../api/guide";
import type { TouristSession } from "../../api/types";
import { EmptyState } from "../../components/common/EmptyState";
import { StatusBadge } from "../../components/common/StatusBadge";

function Heading({kicker,title,text}:{kicker:string;title:string;text:string}){return <header className="page-heading"><span className="page-kicker">{kicker}</span><h1>{title}</h1><p>{text}</p></header>;}
function useSessions(){const [items,setItems]=useState<TouristSession[]>([]);const refresh=()=>guideApi.sessions().then((r)=>setItems(r.items));useEffect(()=>{void refresh();},[]);return{items,refresh};}
function Card({item}:{item:TouristSession}){return <article className="guide-session-card"><div><UserRound size={18}/><StatusBadge tone={item.status==="taken_over"?"success":"warning"}>{item.status}</StatusBadge></div><h3>{item.visitor_name||"匿名游客"}</h3><p>{item.last_question||"尚未提问"}</p><small>{item.location||"未记录地点"} · {item.language}</small><Link to={`/guide/sessions/${item.id}`}>查看会话<ArrowRight size={14}/></Link></article>;}

export function GuideDashboardPage(){const{items}=useSessions();return <section className="page-stack"><Heading kicker="GUIDE DASHBOARD" title="真人导游协同工作台" text="处理游客会话、风险问题和人工接管。"/><div className="guide-stats"><article><RadioTower size={18}/><b>{items.length}</b><span>游客会话</span></article><article><ShieldCheck size={18}/><b>{items.filter((i)=>i.status==="taken_over").length}</b><span>已接管</span></article></div><section className="guide-card-grid">{items.slice(0,6).map((i)=><Card key={i.id} item={i}/>)}</section></section>;}
export function GuideSessionsPage(){const{items}=useSessions();return <section className="page-stack"><Heading kicker="TOURIST SESSIONS" title="游客会话列表" text="查看真实游客会话与当前状态。"/><section className="guide-card-grid">{items.map((i)=><Card key={i.id} item={i}/>)}</section></section>;}

export function GuideSessionDetailPage(){const{id=""}=useParams();const{items,refresh}=useSessions();const[reply,setReply]=useState("");const session=items.find((i)=>i.id===id);const action=async(type:"takeover"|"release")=>{if(type==="takeover")await guideApi.takeover(id);else await guideApi.release(id);refresh();};const send=async()=>{await guideApi.reply(id,reply);setReply("");refresh();};return <section className="page-stack"><Heading kicker="SESSION DETAIL" title="游客会话详情" text="接管、释放并发送真人导游回复。"/>{!session?<EmptyState label="未找到会话"/>:<><section className="session-detail-head"><strong>{session.visitor_name}</strong><StatusBadge>{session.status}</StatusBadge><div className="row-actions"><button onClick={()=>action("takeover")}>人工接管</button><button onClick={()=>action("release")}>释放接管</button></div></section><section className="session-layout"><article className="session-timeline">{session.messages.map((m,index)=><div key={String(m.id??index)}><strong>{String(m.role)}</strong><p>{String(m.question||m.answer||"")}</p></div>)}</article><aside className="guide-reply"><textarea value={reply} onChange={(e)=>setReply(e.target.value)} placeholder="发送真人回复"/><button className="primary" onClick={send}><Send size={15}/>发送</button></aside></section></>}</section>;}

export function GuideTakeoverPage(){const[logs,setLogs]=useState<TakeoverLog[]>([]);useEffect(()=>{guideApi.takeoverLogs().then((r)=>setLogs(r.items));},[]);return <section className="page-stack"><Heading kicker="TAKEOVER CENTER" title="人工接管日志" text="展示游客申请、导游接管与释放记录。"/>{!logs.length?<EmptyState label="暂无接管日志"/>:<div className="history-list">{logs.map((i)=><article key={i.id}><ShieldCheck size={15}/><div><strong>{i.action}</strong><small>{i.session_id.slice(0,10)} · {i.created_at}</small></div></article>)}</div>}</section>;}

export function GuideCorrectionsPage(){const[items,setItems]=useState<GuideCorrection[]>([]);const[form,setForm]=useState({question:"",ai_answer:"",guide_note:""});const refresh=()=>guideApi.corrections().then((r)=>setItems(r.items));useEffect(()=>{void refresh();},[]);const create=async()=>{await guideApi.addCorrection(form);setForm({question:"",ai_answer:"",guide_note:""});refresh();};const close=async(id:string)=>{await guideApi.updateCorrection(id,{status:"resolved"});refresh();};return <section className="page-stack"><Heading kicker="ANSWER CORRECTIONS" title="回答修正" text="提交并维护真实导游修正记录。"/><section className="tech-card form-stack"><textarea value={form.question} onChange={(e)=>setForm({...form,question:e.target.value})} placeholder="游客问题"/><textarea value={form.ai_answer} onChange={(e)=>setForm({...form,ai_answer:e.target.value})} placeholder="优化答案"/><textarea value={form.guide_note} onChange={(e)=>setForm({...form,guide_note:e.target.value})} placeholder="修正依据"/><button className="primary" onClick={create}><BookOpenCheck size={15}/>提交审核</button></section><div className="history-list">{items.map((i)=><article key={i.id}><div><strong>{i.guide_note}</strong><small>{i.optimized_answer}</small></div><button onClick={()=>close(i.id)}>标记完成</button></article>)}</div></section>;}

export function GuideCasesPage(){const[items,setItems]=useState<CollaborationCase[]>([]);const[form,setForm]=useState({case_type:"现场协同",question:"",strategy:"",guide_note:""});const refresh=()=>guideApi.cases().then((r)=>setItems(r.items));useEffect(()=>{void refresh();},[]);const create=async()=>{await guideApi.addCase(form);setForm({...form,question:"",strategy:"",guide_note:""});refresh();};const remove=async(id:string)=>{await guideApi.deleteCase(id);refresh();};return <section className="page-stack"><Heading kicker="GUIDE CASE LIBRARY" title="讲解案例库" text="沉淀可复用的现场服务策略。"/><section className="tech-card form-stack"><input value={form.question} onChange={(e)=>setForm({...form,question:e.target.value})} placeholder="问题"/><textarea value={form.strategy} onChange={(e)=>setForm({...form,strategy:e.target.value})} placeholder="策略"/><button className="primary" onClick={create}><Plus size={15}/>新增案例</button></section><section className="case-grid">{items.map((i)=><article key={i.id}><StatusBadge>{i.case_type}</StatusBadge><h3>{i.question}</h3><p>{i.strategy}</p><button onClick={()=>remove(i.id)}><Trash2 size={14}/></button></article>)}</section></section>;}

export function GuideProfilePage(){const[value,setValue]=useState<GuideProfile>();useEffect(()=>{guideApi.profile().then(setValue);},[]);return <section className="page-stack"><Heading kicker="GUIDE PROFILE" title="导游个人中心" text="展示真实资料与贡献统计。"/>{value&&<><section className="profile-placeholder"><UserRound size={32}/><strong>{value.display_name}</strong><p>{value.bio}</p><small>{value.languages.join(" · ")} / {value.specialties.join(" · ")}</small></section><div className="guide-stats"><article><b>{value.stats.takeovers}</b><span>接管记录</span></article><article><b>{value.stats.replies}</b><span>真人回复</span></article><article><b>{value.stats.corrections}</b><span>知识修正</span></article></div></>}</section>;}
