import { Activity, Database, Plus, RefreshCw, Save, Trash2, UserRound } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { systemApi, type Permission, type Role, type SystemAlert, type SystemMetrics } from "../../api/system";
import type { User, UserRole } from "../../api/types";
import { EmptyState } from "../../components/common/EmptyState";
import { ErrorState } from "../../components/common/ErrorState";
import { LoadingState } from "../../components/common/LoadingState";
import { StatusBadge } from "../../components/common/StatusBadge";
import { useAuth } from "../../store/AuthContext";

type HealthComponent={ok:boolean;host?:string;port?:number;model?:string;engine?:string;backend?:string;error?:string}; type Health={components:Record<string,HealthComponent>}; type LogItem={id:string;capability?:string;provider?:string;model?:string;latency_ms?:number;status?:string;question?:string;created_at?:string};
function Heading({kicker,title,text}:{kicker:string;title:string;text:string}){return <header className="page-heading"><span className="page-kicker">{kicker}</span><h1>{title}</h1><p>{text}</p></header>;}
function Table({heads,children}:{heads:string[];children:React.ReactNode}){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{heads.map((h)=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
function Metrics({value}:{value:SystemMetrics}){return <div className="admin-stats-grid"><Metric label="会话" value={value.sessions}/><Metric label="反馈" value={value.feedback}/><Metric label="模型调用" value={value.model_calls}/><Metric label="RAG 命中率" value={`${Math.round(value.rag_reliable_rate*100)}%`}/></div>;}
function Metric({label,value}:{label:string;value:string|number}){return <article><Database size={18}/><b>{value}</b><span>{label}</span></article>;}

export function SystemDashboardPage(){const [metrics,setMetrics]=useState<SystemMetrics>();const [alerts,setAlerts]=useState<SystemAlert[]>([]);const[error,setError]=useState("");const load=()=>{setError("");systemApi.dashboard().then((r)=>{setMetrics(r.metrics);setAlerts(r.alerts);}).catch((e:Error)=>setError(e.message));};useEffect(()=>{load();},[]);return <section className="page-stack"><section className="system-hero"><div><span className="page-kicker"><Activity size={16}/> SYSTEM OPERATIONS</span><h1>系统运行总览</h1><p>聚合真实运行指标与服务告警。</p></div></section>{!metrics&&!error&&<LoadingState/>}{error&&<ErrorState message={error} retry={load}/>} {metrics&&<Metrics value={metrics}/>}<section className="tech-card"><strong>系统告警</strong>{alerts.length?<div className="history-list">{alerts.map((a)=><article key={a.id}><Activity size={15}/><div><strong>{a.title}</strong><small>{a.detail}</small></div></article>)}</div>:<EmptyState label="当前无系统告警"/>}</section></section>;}

export function SystemUsersPage(){const [items,setItems]=useState<User[]>([]);const [error,setError]=useState("");const [form,setForm]=useState<{username:string;password:string;display_name:string;role:UserRole;language:string}>({username:"",password:"123456",display_name:"",role:"tourist",language:"zh"});const {user,login,logout}=useAuth();const [credentials,setCredentials]=useState({username:"admin",password:"123456"});const refresh=()=>systemApi.users().then((r)=>setItems(r.items)).catch((e:Error)=>setError(e.message));useEffect(()=>{void refresh();},[]);const create=async(e:FormEvent)=>{e.preventDefault();await systemApi.addUser(form);setForm({...form,username:"",display_name:""});refresh();};const remove=async(id:string)=>{await systemApi.deleteUser(id);refresh();};const status=async(item:User)=>{await systemApi.updateUserStatus(item.id,item.status==="active"?"disabled":"active");refresh();};return <section className="page-stack"><Heading kicker="USER ACCESS" title="用户管理" text="新增、启用、停用和删除真实账户。"/><section className="admin-two-col"><form className="tech-card form-stack" onSubmit={create}><input required value={form.username} onChange={(e)=>setForm({...form,username:e.target.value})} placeholder="用户名"/><input value={form.display_name} onChange={(e)=>setForm({...form,display_name:e.target.value})} placeholder="显示名"/><select value={form.role} onChange={(e)=>setForm({...form,role:e.target.value as UserRole})}><option>tourist</option><option>student</option><option>guide</option><option>admin</option></select><button className="primary"><Plus size={15}/>新增用户</button></form><article className="tech-card form-stack">{user?<><p>{user.display_name||user.username} · {user.role}</p><button onClick={logout}>退出登录</button></>:<><input value={credentials.username} onChange={(e)=>setCredentials({...credentials,username:e.target.value})}/><input type="password" value={credentials.password} onChange={(e)=>setCredentials({...credentials,password:e.target.value})}/><button onClick={()=>login(credentials.username,credentials.password)}><UserRound size={15}/>登录</button></>}</article></section>{error&&<ErrorState message={error}/>}<Table heads={["用户","角色","状态","操作"]}>{items.map((item)=><tr key={item.id}><td>{item.display_name||item.username}<small>{item.username}</small></td><td>{item.role}</td><td>{item.status}</td><td><div className="row-actions"><button onClick={()=>status(item)}>{item.status==="active"?"停用":"启用"}</button><button onClick={()=>remove(item.id)}><Trash2 size={14}/></button></div></td></tr>)}</Table></section>;}

export function SystemRolesPage(){const [items,setItems]=useState<Role[]>([]);useEffect(()=>{systemApi.roles().then((r)=>setItems(r.items));},[]);return <section className="page-stack"><Heading kicker="ROLE MANAGEMENT" title="角色管理" text="展示真实角色定义和已分配权限。"/><section className="case-grid">{items.map((item)=><article key={item.id}><StatusBadge>{item.id}</StatusBadge><h3>{item.name}</h3><p>{item.description}</p><small>{item.permissions.join(" · ")}</small></article>)}</section></section>;}

export function SystemPermissionsPage(){const [roles,setRoles]=useState<Role[]>([]);const [permissions,setPermissions]=useState<Permission[]>([]);const [selected,setSelected]=useState("admin");const refresh=()=>Promise.all([systemApi.roles(),systemApi.permissions()]).then(([a,b])=>{setRoles(a.items);setPermissions(b.items);});useEffect(()=>{void refresh();},[]);const role=roles.find((r)=>r.id===selected);const toggle=(id:string)=>{if(!role)return;const next=role.permissions.includes(id)?role.permissions.filter((p)=>p!==id):[...role.permissions,id];setRoles(roles.map((r)=>r.id===role.id?{...r,permissions:next}:r));};const save=async()=>{if(role){await systemApi.updateRolePermissions(role.id,role.permissions);refresh();}};return <section className="page-stack"><Heading kicker="PERMISSION MATRIX" title="权限矩阵" text="按角色配置真实权限。"/><section className="tech-card form-stack"><select value={selected} onChange={(e)=>setSelected(e.target.value)}>{roles.map((r)=><option key={r.id} value={r.id}>{r.name}</option>)}</select>{permissions.map((p)=><label key={p.id}><input type="checkbox" checked={!!role?.permissions.includes(p.id)} onChange={()=>toggle(p.id)}/>{p.name} · {p.module}</label>)}<button className="primary" onClick={save}><Save size={15}/>保存权限</button></section></section>;}

export function SystemHealthPage(){const [value,setValue]=useState<Health>();const[error,setError]=useState("");const refresh=()=>{setError("");systemApi.health().then((r)=>setValue(r as unknown as Health)).catch((e:Error)=>setError(e.message));};useEffect(()=>{refresh();},[]);return <section className="page-stack"><Heading kicker="SERVICE HEALTH" title="服务健康监控" text="检查真实基础设施与模型服务状态。"/><button className="primary compact" onClick={refresh}><RefreshCw size={15}/>刷新</button>{!value&&!error&&<LoadingState/>}{error&&<ErrorState message={error} retry={refresh}/>} {value&&<section className="service-grid">{Object.entries(value.components).map(([name,item])=><article className="service-card" key={name}><strong>{name}</strong><StatusBadge tone={item.ok?"success":"danger"}>{item.ok?"正常":"异常"}</StatusBadge><small>{item.model||item.engine||item.backend||(item.host?`${item.host}:${item.port}`:"")}</small></article>)}</section>}</section>;}

export function SystemLogsPage(){const [models,setModels]=useState<LogItem[]>([]);const [traces,setTraces]=useState<LogItem[]>([]);useEffect(()=>{systemApi.modelLogs().then((r)=>setModels(r.items as LogItem[]));systemApi.requestTraces().then((r)=>setTraces(r.items as LogItem[]));},[]);return <section className="page-stack"><Heading kicker="OBSERVABILITY LOGS" title="调用与请求日志" text="查看真实模型调用和请求链路。"/><Table heads={["能力","Provider","耗时","状态"]}>{models.map((i)=><tr key={i.id}><td>{i.capability}</td><td>{i.provider}/{i.model}</td><td>{i.latency_ms} ms</td><td>{i.status}</td></tr>)}</Table><Table heads={["问题","时间"]}>{traces.map((i)=><tr key={i.id}><td>{i.question}</td><td>{i.created_at}</td></tr>)}</Table></section>;}

export function SystemMetricsPage(){const [value,setValue]=useState<SystemMetrics>();const[error,setError]=useState("");const load=()=>{setError("");systemApi.metrics().then(setValue).catch((e:Error)=>setError(e.message));};useEffect(()=>{load();},[]);return <section className="page-stack"><Heading kicker="SYSTEM METRICS" title="系统指标" text="由真实会话、日志、反馈和 RAG 链路聚合。"/>{!value&&!error&&<LoadingState/>}{error&&<ErrorState message={error} retry={load}/>} {value&&<><Metrics value={value}/><Table heads={["能力","调用","平均耗时","失败"]}>{Object.entries(value.capabilities).map(([name,item])=><tr key={name}><td>{name}</td><td>{item.calls}</td><td>{item.avg_latency_ms} ms</td><td>{item.failed}</td></tr>)}</Table></>}</section>;}

export function SystemSettingsPage(){const [values,setValues]=useState<Record<string,unknown>>({});const [message,setMessage]=useState("");useEffect(()=>{systemApi.settings().then((r)=>setValues(r.values));},[]);const update=(key:string,value:string)=>setValues({...values,[key]:value});const save=async()=>{const r=await systemApi.updateSettings(values);setValues(r.values);setMessage("设置已保存。");};return <section className="page-stack"><Heading kicker="SYSTEM SETTINGS" title="系统设置" text="维护非敏感运行参数。"/><section className="tech-card form-stack">{Object.entries(values).map(([key,value])=><label key={key}>{key}<input value={String(value)} onChange={(e)=>update(key,e.target.value)}/></label>)}<button className="primary" onClick={save}><Save size={15}/>保存设置</button>{message&&<p>{message}</p>}</section></section>;}
