import { Mic, Square, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { touristApi } from "../../api/tourist";
import type { AudioAskResult } from "../../api/types";
import { ErrorState } from "../../components/common/ErrorState";

export function TouristVoicePage(){const[file,setFile]=useState<File>();const[result,setResult]=useState<AudioAskResult>();const[recording,setRecording]=useState(false);const[error,setError]=useState("");const recorder=useRef<MediaRecorder>();const chunks=useRef<Blob[]>([]);
  const start=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];recorder.current=new MediaRecorder(stream);recorder.current.ondataavailable=(e)=>chunks.current.push(e.data);recorder.current.onstop=()=>{const blob=new Blob(chunks.current,{type:"audio/webm"});setFile(new File([blob],"browser-recording.webm",{type:blob.type}));stream.getTracks().forEach((track)=>track.stop());};recorder.current.start();setRecording(true);}catch(reason){setError(reason instanceof Error?reason.message:"无法访问麦克风");}};
  const stop=()=>{recorder.current?.stop();setRecording(false);};const ask=async()=>{if(!file)return;try{setResult(await touristApi.askAudio(file));}catch(reason){setError(reason instanceof Error?reason.message:"语音问答失败");}};
  return <section className="page-stack tourist-service-page tourist-voice-page"><section className="media-banner voice-banner"><div><span className="page-kicker"><Mic size={16}/> VOICE GUIDE</span><h1>边走边问，听见云南</h1><p>可以浏览器内录音，也可以上传音频文件。音频会进入真实 ASR 与 RAG 链路。</p></div></section><section className="media-workspace"><div className="upload-zone"><Mic size={36}/><strong>{file?.name||"尚未选择音频"}</strong><div className="row-actions">{recording?<button className="primary" onClick={stop}><Square size={15}/>停止录音</button>:<button className="primary" onClick={start}><Mic size={15}/>开始录音</button>}<label className="ghost-upload"><Upload size={15}/>选择文件<input type="file" accept="audio/*" onChange={(e)=>setFile(e.target.files?.[0])}/></label></div><button disabled={!file} onClick={ask}>提交语音问答</button></div><article className="result-panel">{error&&<ErrorState message={error}/>} {result&&<><strong>转写</strong><p>{result.transcript.text}</p><strong>回答</strong><p>{result.answer}</p></>}</article></section></section>;}
